# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/decrypt-always-encrypted',
                'doc_host': 'https://vskaret.github.io',
                'git_url': 'https://github.com/vskaret/decrypt-always-encrypted',
                'lib_path': 'decrypt_always_encrypted'},
  'syms': {'decrypt_always_encrypted.core': {'decrypt_always_encrypted.core.foo': ('core.html#foo', 'decrypt_always_encrypted/core.py')}}}
